#!/bin/bash

set -e

echo ""
echo "Running test deployment to development server at dev-01.deploy.local..."
echo ""
cd "$PWD/devops"

# Vagrant may not be running, and might not even be provisioned, so instead of
# just `ansible-playbook deployment.yml -v --limit=deploy_dev --tags=deploy`,
# we set some environment vars for Vagrant and run provision and deployment
# with `vagrant up --provision dev`.
#
# Assuming vagrant has _already_ been provisioned, this is pretty fast.
VAV="v" VAT="deploy" vagrant up --provision dev
